import Head from "next/head";
import styles from "../styles/Home.module.css";
import ThreeScene from "../components/three/three-scene";
import Script from "next/script";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/982762/ccapture.js"></Script>
      </Head>
      <ThreeScene />
    </div>
  );
}
